### ISSUE TITLE
Erro ao carregar carros.json

### ISSUE THREAD

**Issue by NomiasSR** [leonardovilarinho/livro-vue#1]
Olá Leonardo, recentemente adquiri seu livro e estou tendo um problema no exemplo do carros.js. Fiz tudo de acordo com o livro mas estou tento sempre o erro 404 quando tento executar http://localhost:8080/dados/carros.json

Você poderia me dar uma ajuda com relação a esse erro, por gentileza?

Obrigado

**Comment by leonardovilarinho** [comment]
Olá @NomiasSR , você poderia enviar o seu código do capítulo 10 para que eu possa ver?

Pelo que percebi, antes de enviar você pode verificar se o nome da pasta `dados` e do arquivo `carros.json` estão corretos. E se a pasta `dados` está na raiz do projeto, fora da pasta `src` e não dentro dela.

**Comment by NomiasSR** [comment]
eu percebi que a minha configuração do vue está bem diferente da sua... na minha existem arquivos que a sua não tem. Eu peguei o seu projeto e baixei o .zip para a minha máquina, executei o npm install e depois executei com npm run dev e funcionou. Você poderia fazer esse teste no seu micro? É só fazer uma instalação do Vue do zero e depois fazer esse tutorial do capítulo 10. Eu fiz exatamente isso pelo menos 5 vezes mas toda vez fica dando erro 404 no carros.json.  Obrigado.

**Comment by leonardovilarinho** [comment]
Sim, posso sim, antes disso você pode me informar qual a versão do `vue-cli` você está usando? Para ver a versão execute o comando `vue --version`. Pois recentemente o `vue-cli` foi reescrito e toda a estrutura mudou. Daí informando a versão posso refazer o exercício de acordo com ela e lhe mandar atualizado.

**Comment by NomiasSR** [comment]
a versão aqui é 2.9.6

**Comment by leonardovilarinho** [comment]
Refiz o exercício [nesse repositório](https://github.com/leonardovilarinho/vue-livro-servicos-demo), usei a mesma versão do `vue-cli`, se continuar diferente verifique se você está usando o template `webpack-simple` e não outro, craindo o projeto com `vue init webpack-simple <nome-do-projeto>`

**Comment by NomiasSR** [comment]
Blz cara, muito obrigado. Eu queria saber se você dá curso de VUE + JWT + Laravel (principalmente a parte de autenticação com BEARER).

**Comment by leonardovilarinho** [comment]
Eu nunca tentei dar curso não, ás vezes palestro e faço workshops. Mas curso mesmo não, sobre o Laravel + JWT tem um tempo que não uso, acabei migrando pro front-end mesmo e quando preciso de algo no back uso a plataforma do node.

**Comment by NomiasSR** [comment]
ah blz Leonardo, obrigado pela ajuda. Muito bom o teu livro de vue. Sucesso cara e até a próxima.

**Comment by leonardovilarinho** [comment]
Por nada, qualquer coisa só entrar em contato!
